### ISSUE TITLE
Console errors in demo

### ISSUE THREAD

**Issue by jcc10** [freearhey/phash-js#1]
```
magick.js:31 convert: UnableToOpenConfigureFile `colors.xml' @ warning/configure.c/GetConfigureOptions/699.

phash.js:7082 Uncaught (in promise) Error: There is no data for a pixel at [0, 0]
```

I'm not sure what is supposed to happen, but I know it's not that.

**Comment by freearhey** [comment]
Yes, I'm aware of that, but the problem is that the error occurs in one of the dependencies: [KnicKnic/WASM-ImageMagick](https://github.com/KnicKnic/WASM-ImageMagick).

The author has already been notified about this (https://github.com/KnicKnic/WASM-ImageMagick/issues/109) and as soon as some solution appears I will update the package.
